### ISSUE TITLE
Decide on a final API - once and for all

### ISSUE THREAD

**Issue by DesignByOnyx** [bitovi/ylem#148]
This week has been an intense discovery of what ylem should be. The following is a v1 attempt at documentation based development -  the results of which should determine the **usage** of ylem. The following is merely a suggestion for a minimal API:

# ylem 

The most maintainable state management solution for react... period period period. period! (exclamation)

## Usage

There are 2 things you need to know to use ylem:

1. **The observable object:**
    
    Thanks to [Proxies](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy), you can create and update objects using plain JavaScript. The following example defines a person who can become a pop star:

    **person.js**
    
    ```js
    import { ObserveObject } from 'ylem';

    const Person extends ObserveObject {
      constructor({ name }) {
        this.name = name;
      }
      get isPopStar() {
        return ['Timberlake', 'Bieber'].indexOf(this.name.last) > -1;
      }
      makePopStar = () => {
        this.name.last = 'Bieber';
      }
    };
    
    export default Person;
    ```
    Now you can create and update your person using plain JavaScript:
    
    ```js
    import Person from './person';
    
    const person = new Person({
      name: {
        first: 'Justin',
        last: 'Meyer'
      }
    });
    
    person.isPopStar; //-> false
    person.name.last = 'Timberlake';
    person.isPopStar; //-> true
    ```

2. **Decorate your components so that ylem can "watch" for changes:**

	Whenever you render data from an observable object (see above), you must **decorate** your components so that ylem can re-render whenever something changes. Let's take a basic Justin and turn him into a sensation:

    ```js
    import React from 'react';
    import { reactiveComponent } from 'ylem';
    import Person from './person'; // See step 1 above
    
    @reactiveComponent; // <- this is the decorator
    const PersonRenderer extends React.Component {
      constructor(props) {
        super(props);
        this.store = new Person({
          name: { first: 'Justin', last: 'Meyer' });
        });
      }
      
      render() {
        const { name, isPopStar, makePopStar } = this.store;
        return (
          <div onClick={makePopStar}>
            Hello {name.first} {name.last}
            {isPopStar && <p>What color M&Ms do you prefer?</p>}
          </div>
        );
      }
    });
    ```

    > The above component will initially render "Justin Meyer". When you click on his name, he will be converted into a pop star and we can cater to his preference of M&M color!
    
## Advanced usage - Higher order Components (HoC)

If you are familiar with the concept of [HoC](https://reactjs.org/docs/higher-order-components.html), you can `connect` obervable class objects to existing presentation (aka "dumb") components:

```js
import React from 'react';
import { connect } from 'ylem';
import Person from './person'; // See step 1 above

@connect(Person); // <- connect your class to this component
const PersonRenderer = ({ name, isPopStar, makePopStar }) => {
  return (
    <div onClick={makePopStar}>
      Hello {name.first} {name.last}
      {isPopStar && <p>What color M&Ms do you prefer?</p>}
    </div>
  );
};

export default PersonRenderer;
```

Any props passed to your component are made observable!

```js
<PersonRenderer name={{ first: 'Justin', last: 'Meyer' }} />
```

**Comment by BigAB** [comment]
As per our discussion on hangouts, I am all for this change with 2 caveats:

### 1.
Maybe instead of `@reactiveComponent` it could just be the default Ylem export:

```
import React from 'react';
import ylem from 'ylem';
import Person from './person'; // See step 1 above

@ylem // <- this is the decorator
const PersonRenderer extends React.Component {
  constructor(props) {
    super(props);
    this.store = new Person({
      name: { first: 'Justin', last: 'Meyer' });
    });
  }
  
  render() {
    const { name, isPopStar, makePopStar } = this.store;
    return (
      <div onClick={makePopStar}>
        Hello {name.first} {name.last}
        {isPopStar && <p>What color M&Ms do you prefer?</p>}
      </div>
    );
  }
});
````
### 2.
It doesn't have to be on the front page, or whatever, but I think it's important to keep the `createViewModelComponent()` method, even if we rename it to `componentFromObservable` or something, because there's a thing going round right now that HoCs are so last year and render props are the new hawtness:
https://twitter.com/mjackson/status/885910701520207872
https://www.youtube.com/watch?time_continue=4&v=BcVAq3YFiuc
https://reactrocket.com/post/turn-your-hocs-into-render-prop-components/
https://blog.kentcdodds.com/when-to-not-use-render-props-5397bbeff746
>  Fundamentally, render props solves the problem of react component logic code reuse and it solves it in a way that is objectively superior to any other pattern currently. - Kent C Dodds

https://medium.com/tandemly/im-breaking-up-with-higher-order-components-44b0df2db052
So, though I am still unsure about the viewModelComponent, I think they are important to keep, even if we rename them

**Comment by DesignByOnyx** [comment]
I guess it should be worth noting that the "decorator" is just sugar for a factory, which I am ok with using in place of the decorator:

Here's with decorators:

```js
@yelm
const MyComp extends React.Component { ... }
export default MyComp;
```

or as a factory:

```js
const MyComp extends React.Component { ... }
export default ylem(MyComp);
```

The main benefit for the factory (which can also be used as a decorator), is that it works with any component ever: styled components, functional components (render functions), React components, etc:

```js
const SomeFunctionThatReadsAnObservable = ({ foo, bar }) => {
  return <div>{foo} {bar}</div>;
});
export default ylem(SomeFunctionThatReadsAnObservable);
```

**Comment by BigAB** [comment]
This...
```
this.store = {};
```
...turning store into an observable is "magic".

This...
```
@ylem
const PersonRenderer extends React.Component {
```
...is a future-standards based syntax used by [Angular](https://angular.io/), and [many](https://aurelia.io/docs/templating/custom-elements#custom-element-basics)
[other](https://mobx.js.org/) [popular](http://www.typescriptlang.org/docs/handbook/decorators.html) [projects](https://vuejs.org/v2/guide/typescript.html#Class-Style-Vue-Components) [projects](http://react-dnd.github.io/react-dnd/), and there is lot's of information available about decorators via google or stack overflow, and of course can still be used like...
```
const PersonRenderer extends React.Component {
  // ...
}
export default ylem(PersonRenderer)
```

...which incidentally is _my preferred way_ of using it.

RE:
> how this actually makes React.Component update itself is still going to be a mystery

It's still mysterious if they extend the class, unless this is just an extension of the first bullet "decorators aren't understood by most developers", and it's meant as _"Because decorators aren't understood by most developers how React.Component updates itself is still going to be a mystery"_ in which case it should probably be one bullet

RE:
> mixins are useful if they are going to be mixed in on other types. Is this very likely w/i a single app? Maybe mixed-in for `Preact` components?

I am not sure at all what you mean here about Mixins

RE:
> new ObservableObject() - this is arguably more self identifying. However, I think saying ylem.Component has a special store property that re-renders the component whenever it changes, isn't very mysterious. I'm not sure if explicitly calling out new ObservableObject() is worth it. We want it to seem like a normal object in call cases.

Explicitly calling out `ObservableObject` is worth is because that's how it works, and the user assuming it is a normal object _makes_ the magic confusing and set's them up for future troubles.

The magic that `.store` does some setter wizardry to turn into an instance of `ObservableObject` is a lot more magical than the decorator and will most likely cause a lot more frustration when things don't quite work as expected, or show up in the console as a proxy, especially when the users "don't understand whats going on".

Our observables work by having and observer listen for changes and an ObservableObject broadcast changes for the observer to act on. This API presented in this issue (codename: unification) is quite explicit about that, and doesn't try to pretend it works differently.

If you consider the decorator "magic", `ylem.Component` should also be considerer "magic", with the render observation and auto-re-render.

Also, regarding "boilerplate", the decorator/method: by making `.store` the magic property, you now lose the option of making it work with function components, which might have made some simple examples even simpler. You've locked users into always making a full component and putting a single observable on `.store`, which feels like as much boilerplate to me as making them instantiate a new `ObservableObject` instance and decorate a component.

#### Other considerations:

 - extending `ylem.Component` causes trouble with some of react dev tools
 - extending `ylem.Component` disables react-eslint rules for react components

RE:
> Essentially, I see it as:
>
>  - `ylem.Component` adds about 1 point of "magic"
> - `@ylem` adds 2 points, `new ObservableObject()` removes a point

The way I see it:

 - `ylem.Component` adds about 1 point of "magic" and `.store = {}` adds another 1 magic point
 - `@ylem` add 1 point of future-standards based syntax used by many popular projects and will someday be part of the language "magic", and `new ObservableObject` adds clarity as to what is going on and the relationship between the observer and the observable _(personally I also prefer `@observer` to `@ylem`)_.

RE:
> Also, I think beginners more easily identify "things" vs mixins. Ex: "this is a yelm.Component with it's magical .store".

I think it's just as easy for beginners to think: I made this component, adding `@ylem` made it an observer (which will re-render when it should), and I added an observable store as a property.

Honestly if reducing boilerplate is of primary concern, perhaps we should reconsider an old idea you had, and just allow it to take a plain object instead of a Observable Class:
 
 ```js
 /* arguments:
  *   1. ObservableClass / PlainJS Object
  *   2. a render function
  */
 
 export default ylem({ target: 'World' }, ({ target }) => {
    return <h1>Hello { target }</h1>);
 })
 ```
 
 But personally I think the API here (codename: unification) is the best compromise on all fronts, clear without too much magic and easy to progress to the more "advanced" usage of `connect()` and `createComponent()`

**Comment by justinbmeyer** [comment]
I don't consider decorators "magic".  I consider what the decorator does AND `extend ylem.Component` does to be "magic".  

The difference is:

- a decorator is one less thing to get wrong, one less thing to know, and
- extends is easier for the average person to conceptualize

> Explicitly calling out ObservableObject is worth is because that's how it works, and the user assuming it is a normal object makes the magic confusing and set's them up for future troubles.

Ideally, users won't have to know how it works.  Most developers program without the vaguest idea of how their tools actually work. They don't need to know it's an observable object. It could be done with polling like good ol angular 1.  They just need to know they can change a property and the page updates.
